config/routes.rb
Rails.application.routes.draw do
 
  root to: 'home#index'
  devise_for :users
  resources :users
  resources :likes 

  get '/matches', to: 'likes#matches', as: :matches
  get '/profile', to: 'users#profile', as: :profile

  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users
  
  def self.current
    Thread.current[:user]
  end
  def self.current=(user)
    Thread.current[:user] = user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,  :set_current_user
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  private

  def set_current_user
  	User.current = current_user
  end

  protected

  def configure_permitted_parameters
	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:first_name, :last_name, :age, :gender, :city, :state, :vehicle_type,:password, :password_confirmation) }
	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :age, :gender, :city, :state, :vehicle_type, :password, :password_confirmation, :current_password) }
    # devise_parameter_sanitizer.for(:sign_up) << :first_name, :last_name, :age, :gender, :city, :state, :vehicle_type
    # devise_parameter_sanitizer.for(:account_up) << :first_name, :last_name, :age, :gender, :city, :state, :vehicle_type
  end
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def matches
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :set_current_user  #bad practice. Should have been done in the application controller.

  def profile
    @user = current_user # Replace current_user with something???!
  end

  def index
    @users = User.all#where(gender: true)#TODO where gender != current user
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path # Was root path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path
    else 
      render :edit
    end
  end

  def destroy
    @user = User.find(params)
    @user.destroy
    redirect_to users_path
  end

  private

  # def set_current_user
  #   User.current = current_user
  # end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender, :city, :state, :vehicle_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_card.html.erb
<div class="col s12 m4 ">
	<div class="card">
		<div class="card-image waves-effect waves-block waves-light">
		  <img class="activator" src="http://blackhillstrucktrailer.com/wp-content/uploads/2014/05/trucking-industry-addiction-substance-abuse.jpg">
		</div>
		<div class="card-content">
		  <span class="card-title activator grey-text text-darken-4">Person Name<i class="material-icons right">more_vert</i></span><br>
			<i class="material-icons waves-effect waves-red" style="padding-right:10px;">thumb_down</i>
			<i class="material-icons waves-effect waves-green btn-small" style="padding-left:10px; padding-right:5px;">thumb_up</i>
		</div>
		<div class="card-reveal">
		  <span class="card-title grey-text text-darken-4">Person Name<i class="material-icons right">close</i></span>
		  <p>Here is some more information about this person.</p>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<h4 class="center-align">Home</h4>

<div class="row">



</div>

  <!-- Modal Trigger -->
 <!--  <a class="modal-trigger waves-effect waves-light btn" href="#modal1">Modal</a> -->

  <!-- Modal Structure -->
<!--   <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>Are you 18 or older?</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
      <a href="#!" class="modal-action modal-close waves-effect waves-red btn-flat ">DisAgree</a>
    </div>
  </div> -->

<!-- <div class="parallax-container">
  <div class="parallax"><img src="http://magazine.100percentrock.com/wp-content/uploads/2013/06/Trucker-Diablo.jpg"></div>
</div> -->

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
<nav>
  <div class="nav-wrapper brown lighten-1">
    <a href="/" class="brand-logo">Trucker's Only</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/">Browse</a></li>
      <li><%= link_to 'Likes', likes_path %></li>
      <li><%= link_to 'Matches', matches_path %></li>
      <li><%= link_to 'My Profile', profile_path %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="/">Browse</a></li>
     <li><%= link_to 'Likes', likes_path %></li>
      <li><%= link_to 'Matches', matches_path %></li>
      <li><%= link_to 'My Profile', profile_path %></li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    </ul>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truckers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Materialize Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<%= render "layouts/navbar" %>
<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/likes/edit.html.erb
<h1>Likes#edit</h1>
<p>Find me in app/views/likes/edit.html.erb</p>

app/views/likes/index.html.erb
<h4 class="center-align">Likes</h4>

<div class="row">
	<%= render 'home/card' %>
</div>

app/views/likes/matches.html.erb
<h4 class="center-align">Matches</h4>

<div class="row">
	<%= render 'home/card' %>
</div>

app/views/likes/show.html.erb
<h4 class="center-align">Likes</h4>

app/views/users/_user_form.html.erb
<%= form_for :users do |f| %>
<div class="row">
    <div class="field col s12 m6">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>

    <div class="field col s12 m6">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
  </div>

  <div class="row">
    <div class="field col s12 m3">
      <%= f.label :age %><br />
      <%= f.number_field :age %>
    </div>

    <div class="field col s12 m3">
      <%= f.label :gender %><br />
      <%= f.text_field :gender %>
    </div>

    <div class="field col s12 m3">
      <%= f.label :city %><br />
      <%= f.text_field :city %>
    </div>

    <div class="field col s12 m3">
      <%= f.label :state %><br />
      <%= f.text_field :state %>
    </div>
  </div><br>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

<!-- TODO: make radio button functional -->
  <div class="field col s12 m3 center-align"> 
  What kind of vehicle do you drive?
    <input class='with-gap' name="group1" type="radio" id="test1" />
    <label for="test1">Manual</label>
    <input class='with-gap' name="group1" type="radio" id="test2" />
    <label for="test2">Automatic</label>   
  </div>


  <div class="actions right-align">
    <%= f.submit "Confirm" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="center-align">Your Profile</h1>

<%= render 'user_form' %>

app/views/users/index.html.erb
<h1 class="center-align">You're on this pages somehow</h1>

app/views/users/profile.html.erb
<h4 class="center-align">Your Profile</h4>

<div class="right-align">
<%= link_to 'Edit', edit_user_registration_path %>
</div>

<%= form_for :users do |f| %>

First Name: <%= @user.first_name %><br>
Last Name: <%= @user.last_name %><br>
Age: <%= @user.age %><br>
Email: <%= current_user.email %><br>
Gender: <%= @user.gender %><br>
City: <%= @user.city %><br>
State: <%= @user.state %><br>
Vehicle Type: <%= @user.vehicle_type %><br>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>